name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-13
          - target: aarch64-apple-darwin
            os: macos-14

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Create archive and checksum
        shell: bash
        run: |
          archive="rustbrother-${{ matrix.target }}.tar.gz"
          tar -czf "$archive" -C "./target/${{ matrix.target }}/release" rustbrother

          # Use different checksum commands for different OS
          if [[ "${{ runner.os }}" == "macOS" ]]; then
            shasum -a 256 "$archive" > "${archive}.sha256"
          else
            sha256sum "$archive" > "${archive}.sha256"
          fi

          echo "ARCHIVE=$archive" >> $GITHUB_ENV
          echo "CHECKSUM=${archive}.sha256" >> $GITHUB_ENV

      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.ARCHIVE }}
            ${{ env.CHECKSUM }}
          generate_release_notes: true
