name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: rustbrother
            asset_name: rustbrother-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: rustbrother.exe
            asset_name: rustbrother-windows-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: rustbrother
            asset_name: rustbrother-darwin-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: rustbrother
            asset_name: rustbrother-darwin-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Strip binary (Unix)
        if: matrix.os != 'windows-latest'
        run: strip target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

      - name: Create tarball (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          tar czf ${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }}

      - name: Create zip (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          7z a ${{ matrix.asset_name }}.zip ${{ matrix.artifact_name }}

      - name: Generate checksums
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          sha256sum ${{ matrix.asset_name }}.tar.gz > ${{ matrix.asset_name }}.tar.gz.sha256

      - name: Generate checksums (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          certutil -hashfile ${{ matrix.asset_name }}.zip SHA256 | findstr /v "hash" | findstr /v "SHA256" > ${{ matrix.asset_name }}.zip.sha256

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/${{ matrix.asset_name }}.tar.gz
            target/${{ matrix.target }}/release/${{ matrix.asset_name }}.zip
            target/${{ matrix.target }}/release/${{ matrix.asset_name }}.tar.gz.sha256
            target/${{ matrix.target }}/release/${{ matrix.asset_name }}.zip.sha256
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
